In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("G:/Externship files/Fish.csv")

In [3]:
data.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [4]:
data.shape

(159, 7)

In [5]:
data.isnull()

Species  Weight  Length1  Length2  Length3  Height  Width
0      False   False    False    False    False   False  False
1      False   False    False    False    False   False  False
2      False   False    False    False    False   False  False
3      False   False    False    False    False   False  False
4      False   False    False    False    False   False  False
..       ...     ...      ...      ...      ...     ...    ...
154    False   False    False    False    False   False  False
155    False   False    False    False    False   False  False
156    False   False    False    False    False   False  False
157    False   False    False    False    False   False  False
158    False   False    False    False    False   False  False

[159 rows x 7 columns]

In [6]:
data.isnull().any()

Species    False
Weight     False
Length1    False
Length2    False
Length3    False
Height     False
Width      False
dtype: bool

In [7]:
data.isnull().sum()

Species    0
Weight     0
Length1    0
Length2    0
Length3    0
Height     0
Width      0
dtype: int64

In [11]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data["Species"]=le.fit_transform(data["Species"])



In [12]:
data.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0        0   242.0     23.2     25.4     30.0  11.5200  4.0200
1        0   290.0     24.0     26.3     31.2  12.4800  4.3056
2        0   340.0     23.9     26.5     31.1  12.3778  4.6961
3        0   363.0     26.3     29.0     33.5  12.7300  4.4555
4        0   430.0     26.5     29.0     34.0  12.4440  5.1340

In [19]:
x=data.iloc[:,2:6].values
y=data.iloc[:,6].values

In [20]:
x

array([[23.2   , 25.4   , 30.    , 11.52  ],
       [24.    , 26.3   , 31.2   , 12.48  ],
       [23.9   , 26.5   , 31.1   , 12.3778],
       [26.3   , 29.    , 33.5   , 12.73  ],
       [26.5   , 29.    , 34.    , 12.444 ],
       [26.8   , 29.7   , 34.7   , 13.6024],
       [26.8   , 29.7   , 34.5   , 14.1795],
       [27.6   , 30.    , 35.    , 12.67  ],
       [27.6   , 30.    , 35.1   , 14.0049],
       [28.5   , 30.7   , 36.2   , 14.2266],
       [28.4   , 31.    , 36.2   , 14.2628],
       [28.7   , 31.    , 36.2   , 14.3714],
       [29.1   , 31.5   , 36.4   , 13.7592],
       [29.5   , 32.    , 37.3   , 13.9129],
       [29.4   , 32.    , 37.2   , 14.9544],
       [29.4   , 32.    , 37.2   , 15.438 ],
       [30.4   , 33.    , 38.3   , 14.8604],
       [30.4   , 33.    , 38.5   , 14.938 ],
       [30.9   , 33.5   , 38.6   , 15.633 ],
       [31.    , 33.5   , 38.7   , 14.4738],
       [31.3   , 34.    , 39.5   , 15.1285],
       [31.4   , 34.    , 39.2   , 15.9936],
       [31

In [21]:
y

array([4.02  , 4.3056, 4.6961, 4.4555, 5.134 , 4.9274, 5.2785, 4.69  ,
       4.8438, 4.9594, 5.1042, 4.8146, 4.368 , 5.0728, 5.1708, 5.58  ,
       5.2854, 5.1975, 5.1338, 5.7276, 5.5695, 5.3704, 5.2801, 6.1306,
       5.589 , 6.0532, 6.09  , 5.8515, 6.1984, 6.603 , 6.3063, 6.292 ,
       6.7497, 6.7473, 6.3705, 2.268 , 2.8217, 2.9044, 3.1746, 3.5742,
       3.3516, 3.3957, 3.2943, 3.7544, 3.5478, 3.8203, 3.325 , 3.8   ,
       3.8352, 3.6312, 4.1272, 3.906 , 4.4968, 4.7736, 5.355 , 4.2476,
       4.2485, 4.6816, 6.562 , 6.5736, 6.525 , 2.3265, 2.3142, 2.673 ,
       2.9181, 3.2928, 3.2944, 3.4104, 3.1571, 3.6636, 4.144 , 4.234 ,
       1.408 , 1.9992, 2.432 , 2.6316, 2.9415, 3.3216, 3.1234, 3.0502,
       3.0368, 2.772 , 3.555 , 3.3075, 3.6675, 3.534 , 3.4075, 3.525 ,
       3.525 , 3.525 , 3.995 , 3.624 , 3.624 , 3.63  , 3.626 , 3.725 ,
       3.723 , 3.825 , 4.1658, 3.6835, 4.239 , 4.144 , 5.1373, 4.335 ,
       4.335 , 4.5662, 4.2042, 4.6354, 4.7716, 6.018 , 6.3875, 7.7957,
      

In [22]:
x.shape

(159, 4)

In [23]:
y.shape

(159,)

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [25]:
x_train.shape

(127, 4)

In [26]:
x_test.shape

(32, 4)

In [28]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [29]:
x_train

array([[ 3.17091789e+00,  3.13904375e+00,  2.98953375e+00,
         1.65693045e-01],
       [ 7.32808723e-01,  7.00466821e-01,  7.34116902e-01,
        -6.72599948e-01],
       [ 4.92137003e-01,  5.05380667e-01,  6.89366567e-01,
         1.36936060e+00],
       [-3.86837976e-01, -3.72507027e-01, -4.56241991e-01,
        -3.62187165e-01],
       [ 1.25897428e-01,  8.59454356e-02, -4.45389154e-02,
        -2.95326914e-01],
       [ 6.07240869e-01,  6.51695282e-01,  8.14667504e-01,
         1.52090593e+00],
       [ 8.68840565e-01,  7.98009898e-01,  6.89366567e-01,
         3.96592013e-01],
       [-5.96117732e-01, -5.67593181e-01, -6.35243328e-01,
        -6.86649296e-01],
       [ 5.02600991e-01,  4.85872051e-01,  3.04513692e-01,
         2.64084241e-01],
       [-1.24488498e+00, -1.25039472e+00, -1.30649834e+00,
        -1.15595242e+00],
       [-3.86837976e-01, -3.72507027e-01, -4.56241991e-01,
        -5.72240928e-01],
       [ 7.32808723e-01,  7.98009898e-01,  9.75768707e-01,
      